name: fox_note_app
description: A new Flutter project.

publish_to: 'none' 

version: 2.0.0+2

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  entry: ^0.0.2+2
  flutter_launcher_icons: ^0.8.1
  fluttertoast: null
  intl: ^0.17.0
  linkable: ^2.0.0
  modal_bottom_sheet: null
  path_provider: ^2.0.1
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  