name: fox_note_app
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  entry: ^0.0.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  fluttertoast: ^8.0.8
  google_fonts: ^2.2.0
  intl: ^0.17.0
  linkable: ^3.0.1
  modal_bottom_sheet: ^2.0.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  roundcheckbox: ^2.0.4+1
  share: ^2.0.4
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
